
[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btclog"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/websocket"

[[constraint]]
  branch = "master"
  name = "github.com/decred/bitset"

[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrd"

[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrrpcclient"

[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrutil"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/jrick/logrotate"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.0.0"
